apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ Values.MarketMaker.name }}
  labels:
    app: {{ Values.AppName }}

spec:
  replicas: 12
  selector:
    matchLabels:
      app: {{ Values.AppName }}
  template:
    metadata:
      labels:
        app: {{ Values.MarketMaker.name }}
    spec:
      containers:
      - name:
        image: localhost:5000/trader
        imagePullPolicy: Never
        ports:
        - containerPort: {{ Values.MarketMaker.service.port }}
